CREATE TABLE user_details (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  VARCHAR(255),
    full_name  VARCHAR(255),
    email      VARCHAR(255),
    gender     VARCHAR(255),
    avatar_url VARCHAR(255),
    role       VARCHAR(255),
    created_at DATE,
    updated_at DATE
);

CREATE TABLE fitness_details (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL UNIQUE REFERENCES user_details(id),
    age                    INTEGER NOT NULL,
    height                 NUMERIC(38, 2) NOT NULL,
    weight                 NUMERIC(38, 2) NOT NULL,
    activity_level         VARCHAR(255) NOT NULL,
    target_weight_kg       NUMERIC(38, 2) NOT NULL,
    target_date            DATE NOT NULL,
    daily_calorie_target   INTEGER NOT NULL,
    daily_protein_target_g NUMERIC(38, 2) NOT NULL,
    daily_carbs_target_g   NUMERIC(38, 2) NOT NULL,
    daily_fat_target_g     NUMERIC(38, 2) NOT NULL,
    ai_coach_advice        VARCHAR(255) NOT NULL
);
